import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const CONTRACTS_JSON = resolve(HERE, "..", "..", "..", "contracts.json");
const JSON_OUT = resolve(HERE, "..", "addresses.json");
const TS_OUT = resolve(HERE, "generated-addresses.ts");

// devnet is an internal anvil fork that resets without warning, so it is not
// part of the published surface.
const PUBLISHED_ENVIRONMENTS = ["testnet", "mainnet"] as const;

// Operational fields that describe how *we* run infrastructure, not where the
// protocol lives. Everything else in a chain entry is published verbatim.
const INTERNAL_CHAIN_FIELDS = new Set(["anvilUrl", "maxReorgDepth", "forkedFromChain"]);

type ChainEntry = Record<string, unknown>;
type EnvEntry = Record<string, ChainEntry>;

const source: Record<string, EnvEntry> = JSON.parse(await readFile(CONTRACTS_JSON, "utf-8"));

const addresses: Record<string, EnvEntry> = {};
for (const env of PUBLISHED_ENVIRONMENTS) {
  const chains = source[env];
  if (!chains) throw new Error(`contracts.json is missing the "${env}" environment`);

  addresses[env] = {};
  for (const [chainName, chain] of Object.entries(chains)) {
    addresses[env][chainName] = Object.fromEntries(
      Object.entries(chain).filter(([key]) => !INTERNAL_CHAIN_FIELDS.has(key)),
    );
  }
}

await writeFile(JSON_OUT, `${JSON.stringify(addresses, null, 2)}\n`);

const banner = `// Generated by src/gen-addresses.ts from the monorepo's contracts.json.
// Do not edit by hand — run \`just abi\` (or \`bun run addresses\`) instead.
`;
await writeFile(
  TS_OUT,
  `${banner}\nexport const addresses = ${JSON.stringify(addresses, null, 2)} as const;\n`,
);

const chainCount = PUBLISHED_ENVIRONMENTS.reduce(
  (total, env) => total + Object.keys(addresses[env]).length,
  0,
);
console.log(
  `\nWrote ${chainCount} chains across ${PUBLISHED_ENVIRONMENTS.length} environments to addresses.json + src/generated-addresses.ts`,
);
